liteos_c_args = [
    '-DLOSCFG_LIBC_NEWLIB=1',
    '-DLOSCFG_POSIX_API=1',
]

liteos_incdirs = include_directories(
    'arch/include',
    'arch/arm/common',
    'arch/arm/include',
    'arch/arm/cortex-m4/gcc',
    'components/shell/include',
    'kal/cmsis',
    'kal/libc/newlib/porting/include',
    'kal/libc/newlib/porting/include/sys',
    'kal/posix/include',
    'kernel/include',
    'utils',
    'utils/internal',
    'third_party/bounds_checking_function/include',
    'third_party/cmsis/CMSIS/RTOS2/Include',
    'components/backtrace',
    'components/cpup',
    'components/exchook',
    'components/power',
    'components/signal'    
)

liteos_sources = files(
    'arch/arm/common/los_common_interrupt.c',
    'arch/arm/cortex-m4/gcc/los_context.c',
    'arch/arm/cortex-m4/gcc/los_dispatch.S',
    'arch/arm/cortex-m4/gcc/los_exc.S',
    'arch/arm/cortex-m4/gcc/los_interrupt.c',
    'arch/arm/cortex-m4/gcc/los_mpu.c',
    'arch/arm/cortex-m4/gcc/los_timer.c',
    'components/backtrace/los_backtrace.c',
    'components/cpup/los_cpup.c',
    'components/exchook/los_exc_info.c',
    'components/exchook/los_exchook.c',
    'components/power/los_pm.c',
    'components/shell/src/base/shcmd.c',
    'components/shell/src/base/shcmdparse.c',
    'components/shell/src/base/shmsg.c',
    'components/shell/src/base/show.c',
    'components/shell/src/cmds/date_shell.c',
    'components/shell/src/cmds/fullpath.c',
    'components/shell/src/cmds/mempt_shellcmd.c',
    'components/shell/src/cmds/shell_shellcmd.c',
    'components/shell/src/cmds/task_shellcmd.c',
    'components/shell/src/cmds/vfs_shellcmd.c',
    'components/signal/los_signal.c',
    'kal/cmsis/cmsis_liteos2.c',
    'kal/libc/newlib/porting/src/hook_adapt.c',
    'kal/libc/newlib/porting/src/network/htonl.c',
    'kal/libc/newlib/porting/src/network/htons.c',
    'kal/libc/newlib/porting/src/network/ntohl.c',
    'kal/libc/newlib/porting/src/network/ntohs.c',
    'kal/posix/src/errno.c',
    'kal/posix/src/libc.c',
    'kal/posix/src/semaphore.c',
    'kal/posix/src/mqueue.c',
    'kal/posix/src/malloc.c',
    'kal/posix/src/pthread_attr.c',
    'kal/posix/src/time.c',
    'kal/posix/src/pthread.c',
    'kal/posix/src/signal.c',
    'kal/posix/src/map_error.c',
    'kal/posix/src/pthread_mutex.c',
    'kal/posix/src/poll.c',
    'kal/posix/src/pthread_cond.c',
    'kal/posix/src/pipe.c',
    'kernel/src/los_event.c',
    'kernel/src/los_init.c',
    'kernel/src/los_mux.c',
    'kernel/src/los_queue.c',
    'kernel/src/los_sched.c',
    'kernel/src/los_sem.c',
    'kernel/src/los_sortlink.c',
    'kernel/src/los_swtmr.c',
    'kernel/src/los_task.c',
    'kernel/src/los_tick.c',
    'kernel/src/mm/los_membox.c',
    'kernel/src/mm/los_memory.c',
    'third_party/bounds_checking_function/src/fscanf_s.c',
    'third_party/bounds_checking_function/src/fwscanf_s.c',
    'third_party/bounds_checking_function/src/gets_s.c',
    'third_party/bounds_checking_function/src/memcpy_s.c',
    'third_party/bounds_checking_function/src/memmove_s.c',
    'third_party/bounds_checking_function/src/memset_s.c',
    'third_party/bounds_checking_function/src/scanf_s.c',
    'third_party/bounds_checking_function/src/securecutil.c',
    'third_party/bounds_checking_function/src/secureinput_a.c',
    'third_party/bounds_checking_function/src/secureinput_w.c',
    'third_party/bounds_checking_function/src/secureprintoutput_a.c',
    'third_party/bounds_checking_function/src/secureprintoutput_w.c',
    'third_party/bounds_checking_function/src/snprintf_s.c',
    'third_party/bounds_checking_function/src/sprintf_s.c',
    'third_party/bounds_checking_function/src/sscanf_s.c',
    'third_party/bounds_checking_function/src/strcat_s.c',
    'third_party/bounds_checking_function/src/strcpy_s.c',
    'third_party/bounds_checking_function/src/strncat_s.c',
    'third_party/bounds_checking_function/src/strncpy_s.c',
    'third_party/bounds_checking_function/src/strtok_s.c',
    'third_party/bounds_checking_function/src/swprintf_s.c',
    'third_party/bounds_checking_function/src/swscanf_s.c',
    'third_party/bounds_checking_function/src/vfscanf_s.c',
    'third_party/bounds_checking_function/src/vfwscanf_s.c',
    'third_party/bounds_checking_function/src/vscanf_s.c',
    'third_party/bounds_checking_function/src/vsnprintf_s.c',
    'third_party/bounds_checking_function/src/vsprintf_s.c',
    'third_party/bounds_checking_function/src/vsscanf_s.c',
    'third_party/bounds_checking_function/src/vswprintf_s.c',
    'third_party/bounds_checking_function/src/vswscanf_s.c',
    'third_party/bounds_checking_function/src/vwscanf_s.c',
    'third_party/bounds_checking_function/src/wcscat_s.c',
    'third_party/bounds_checking_function/src/wcscpy_s.c',
    'third_party/bounds_checking_function/src/wcsncat_s.c',
    'third_party/bounds_checking_function/src/wcsncpy_s.c',
    'third_party/bounds_checking_function/src/wcstok_s.c',
    'third_party/bounds_checking_function/src/wmemcpy_s.c',
    'third_party/bounds_checking_function/src/wmemmove_s.c',
    'third_party/bounds_checking_function/src/wscanf_s.c',
    'utils/los_debug.c',
    'utils/los_error.c',
    'utils/los_hook.c'
)