RM := rm -rf
BRIDGE_EXE := studio-mdk-bridge.exe
UV4_EXE := "E:\software\keil\UV4\UV4.exe"
UVPROJX_LOC := "D:\SCM\git\keil\gd32\gd32f450ik\project.uvprojx"

.PHONY: mdk_all

mdk_all:
	-$(BRIDGE_EXE) --build --uv4-path $(UV4_EXE) $(UVPROJX_LOC)

mdk_clean:
	-@$(RM) *
	@echo 'success'



*.elf: $(wildcard ..)
